export const projects = [
    {
        id: 1,
        divId: "cleaner",
        appLink: "https://www.allclear-windowcleaning.co.uk/",
        appName: "All Clear Window Cleaning",
        appDescription: "A single-page website was required for a client whose decade-old website only contained one image and was not ranking on Google at all. I used WIX to build a mobile-optimised webpage that now ranks on page one for window cleaners in Exeter",
        icon1: "bi bi-gear-fill animate-icon",
        tech1: "Wix",
        icon2: "bi bi-envelope-check-fill",
        tech2: "Leads",
        icon3: "bi bi-graph-up-arrow",
        tech3: "SEO"
    },
    {
        id: 2,
        divId: "fuel-calculator",
        appLink: "https://r0bsaunders.github.io/fuel-cost-and-sell-price-calculator-application/",
        appName: "Fuel Cost Calculator",
        appDescription: "In order to make my own day-job easier, I created an app for myself that lets me calculate the cost of fuel for my various clients taking into account the cost to buy, the desired profit margin and the delivery cost per litre",
        icon1: "bi bi-gear-fill",
        tech1: "Wix",
        icon2: "bi bi-check-circle-fill",
        tech2: "Practical",
        icon3: "bi bi-github animate-icon",
        tech3: "GitHub"
    },
    {
        id: 3,
        divId: "weather",
        appLink: "https://r0bsaunders.github.io/Interactive-5-day-weather-forecast/",
        appName: "Weather forecast app",
        appDescription: "A single-page website was required for a client whose decade-old website only contained one image and was not ranking on Google at all. I used WIX to build a mobile-optimised webpage that now ranks on page one for window cleaners in Exeter",
        icon1: "bi bi-link animate-icon",
        tech1: "API",
        icon2: "bi bi-envelope-check-fill",
        tech2: "Dynamic",
        icon3: "bi bi-graph-up-arrow",
        tech3: "Convenient"
    },
    {
        id: 4,
        divId: "cleaner",
        appLink: "https://www.allclear-windowcleaning.co.uk/",
        appName: "All Clear Window Cleaning",
        appDescription: "A single-page website was required for a client whose decade-old website only contained one image and was not ranking on Google at all. I used WIX to build a mobile-optimised webpage that now ranks on page one for window cleaners in Exeter",
        icon1: "bi bi-gear-fill animate-icon",
        tech1: "Wix",
        icon2: "bi bi-envelope-check-fill",
        tech2: "Lead Generating",
        icon3: "bi bi-graph-up-arrow",
        tech3: "SEO"
    },
    {
        id: 5,
        divId: "cleaner",
        appLink: "https://www.allclear-windowcleaning.co.uk/",
        appName: "All Clear Window Cleaning",
        appDescription: "A single-page website was required for a client whose decade-old website only contained one image and was not ranking on Google at all. I used WIX to build a mobile-optimised webpage that now ranks on page one for window cleaners in Exeter",
        icon1: "bi bi-gear-fill animate-icon",
        tech1: "Wix",
        icon2: "bi bi-envelope-check-fill",
        tech2: "Lead Generating",
        icon3: "bi bi-graph-up-arrow",
        tech3: "SEO"
    },
    {
        id: 6,
        divId: "cleaner",
        appLink: "https://www.allclear-windowcleaning.co.uk/",
        appName: "All Clear Window Cleaning",
        appDescription: "A single-page website was required for a client whose decade-old website only contained one image and was not ranking on Google at all. I used WIX to build a mobile-optimised webpage that now ranks on page one for window cleaners in Exeter",
        icon1: "bi bi-gear-fill animate-icon",
        tech1: "Wix",
        icon2: "bi bi-envelope-check-fill",
        tech2: "Lead Generating",
        icon3: "bi bi-graph-up-arrow",
        tech3: "SEO"
    },

]