export const projects = [
    // Each object contains the content for the projects pageXOffset. 
    {
        id: 1,
        divId: "cleaner",
        appLink: "https://www.allclear-windowcleaning.co.uk/",
        appName: "All Clear Window Cleaning",
        appDescription: "A single-page website was required for a client whose decade-old website only contained one image and was not ranking on Google at all. I used WIX to build a mobile-optimised webpage that now ranks on page one for window cleaners in Exeter",
        icon1: "bi bi-gear-fill animate-icon",
        tech1: "Wix",
        icon2: "bi bi-envelope-check-fill",
        tech2: "Leads",
        icon3: "bi bi-graph-up-arrow",
        tech3: "SEO"
    },
    {
        id: 2,
        divId: "fuel-calculator",
        appLink: "https://r0bsaunders.github.io/fuel-cost-and-sell-price-calculator-application/",
        appName: "Fuel Cost Calculator",
        appDescription: "In order to make my own day-job easier, I created an app for myself that lets me calculate the cost of fuel for my various clients taking into account the cost to buy, the desired profit margin and the delivery cost per litre",
        icon1: "bi bi-tools",
        tech1: "Bespoke",
        icon2: "bi bi-check-circle-fill",
        tech2: "Practical",
        icon3: "bi bi-github animate-icon",
        tech3: "GitHub",
        github:"https://github.com/R0bsaunders/fuel-cost-and-sell-price-calculator-application"
    },
    {
        id: 3,
        divId: "weather",
        appLink: "https://r0bsaunders.github.io/Interactive-5-day-weather-forecast/",
        appName: "Weather forecast app",
        appDescription: "A single-page website was required for a client whose decade-old website only contained one image and was not ranking on Google at all. I used WIX to build a mobile-optimised webpage that now ranks on page one for window cleaners in Exeter",
        icon1: "bi bi-link",
        tech1: "API",
        icon2: "bi bi-envelope-check-fill",
        tech2: "Dynamic",
        icon3: "bi bi-github animate-icon",
        tech3: "GitHub",
        github: "https://github.com/R0bsaunders/Interactive-5-day-weather-forecast"
    },
    {
        id: 4,
        divId: "simon-tutty",
        appLink: "https://www.simontutty.co.uk/",
        appName: "Simon Tutty Photography",
        appDescription: "Simon's original website consisted of a few pages with no text content - only pictures. While you might expect this on a photography website, it meant his search engine presence was non-existent. I used his current Squarespace account to create a new website with up to date UX and most importantly, content that ranks his website high on Google for some very relevant keywords.",
        icon1: "bi bi-gear-fill animate-icon",
        tech1: "SquareSpace",
        icon2: "bi bi-envelope-check-fill",
        tech2: "Lead Generating",
        icon3: "bi bi-graph-up-arrow",
        tech3: "SEO"
    },
    {
        id: 5,
        divId: "planner",
        appLink: "https://r0bsaunders.github.io/robs-javascript-powered-todo-daily-planner/",
        appName: "JavaScript To Do List",
        appDescription: "As a demonstration of knowledge learn to date, I built a to do list that integrates with moment.js to style blocks in the past and the present block in a different colour to the blocks that are in the future. The code remembers any entry the user makes so that they can navigate back to it through out the day (as long a they don't close their browser)",
        icon1: "bi bi-tools",
        tech1: "Bespoke",
        icon2: "bi bi-check-circle-fill",
        tech2: "Practical",
        icon3: "bi bi-github animate-icon",
        tech3: "GitHub",
        github: "https://github.com/R0bsaunders/robs-javascript-powered-todo-daily-planner"
    },
    {
        id: 6,
        divId: "saleyha",
        appLink: "http://saleyhaa.sg-host.com/",
        appName: "Saleyha Ahsan Portfolio",
        appDescription: "Saleyha is an incredible person and inspirational woman who was let down by her previous web-developer (an agency in London). I used WordPress and Elementor to create her a website that she manage herself and that looks modern and professional, reflecting on her own professionalism.",
        icon1: "bi bi-wordpress animate-icon",
        tech1: "Wordpress",
        icon2: "bi bi-envelope-check-fill",
        tech2: "Lead Generating",
        icon3: "bi bi-filetype-css",
        tech3: "CSS"
    },
];